version: '3.3'

services:
  db:
    build: ./mysql/
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3307:3306"
    networks:
      - dockercompose
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/init.sql

  flask:
    depends_on:
      - db
    build: ./flask/
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - /Users/victormussio/Desktop/Projects/Curso Docker/compose/bind_mount_compose/flask:/app
    networks:
      - dockercompose

networks:
  dockercompose: